version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-app}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
