version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - service
  events-api:
    build:
      context: .
    container_name: events-api
    ports:
      - 2424:2424
    restart: always
    image: hub.docker.com/repository/docker/edvaljunior/application_docker_terraform_ec2_ansible/general
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/meubanco
    depends_on:
      - db
    networks:
      - service

volumes:
  db_data:

networks:
  service:
    driver: bridge
