version: '3.8'
services:
  events-api:
    build: .
    container_name: events-api
    ports:
      - 3000:3000
    restart: always
    image: hub.docker.com/repository/docker/edvaljunior/application_docker_terraform_ec2_ansible/general


