version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - service

  events-api:
    image: ${DOCKER_IMAGE:-ghcr.io/pedrobarros3421/terraform_ansible_ec2_application/server:latest}
    container_name: events-api
    entrypoint: ['npm', 'start']
    restart: always
    ports:
      - '2424:2424'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/meubanco
      PORT: 2424
    depends_on:
      - db
    networks:
      - service

volumes:
  db_data:

networks:
  service:
    driver: bridge
