version: "3.8"
services:
  events-api:
    image: "edvaljunior/application_docker_terraform_ec2_ansible:latest"
    container_name: events-api
    ports:
      - 2424:2424
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/meubanco

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
