---
- name: Instalar Docker
  hosts: localhost
  become: true
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Garantir que o serviço Docker está ativo e habilitado
      service:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário atual ao grupo docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
